---
title: "Vole Green Unispec-SC files"
author: "Ruby An"
date: "July 16, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Set-up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(googlesheets4)
```

## Unispec-SC Functions

```{r functions}
## Spectral Band Definitions
band_defns <- tribble(
  ~definition, ~color, ~min, ~max,
  "ITEX", "red", 560, 600,
  "ITEX", "nir", 725, 1000,
  "MODIS", "red", 620, 670, 
  "MODIS", "nir", 841, 876,
  "MODIS", "blue", 459,479,
  "SKYE", "red", 620, 680,
  "SKYE", "nir", 830, 880,
  "SKYE", "blue", 455, 480,
  "ToolikGIS_Drone_2018", "red", 640, 680,
  "ToolikGIS_Drone_2018", "nir", 820, 890,
  "ToolikGIS_MicaSense_2019", "blue", 455, 495,
  "ToolikGIS_MicaSense_2019", "green", 540, 580,
  "ToolikGIS_MicaSense_2019", "red", 658, 678,
  "ToolikGIS_MicaSense_2019", "red_edge", 707, 727,
  "ToolikGIS_MicaSense_2019", "near_ir", 800, 880,
  "ToolikEDC", "red", 560, 680,
  "ToolikEDC", "nir", 725, 1000
)
calculate_indices <- function(spectra, band_defns, instrument = "MODIS", indices = "NDVI") {
  # Calculates NDVI, EVI, and EVI2 from dataframe including Wavelength : Spectra 
  ## inputs: spectra - Wavelength, Reflectance columns
  ##         band_defns : wavelengths definining colors 
  ##         instrument : e.g. MODIS, SKYE, ITEX
  ##         indicies   : the index to return 
  ## output: dataframe with Index : Value
  
  bands <- band_defns %>% 
    filter(definition == instrument) 
  
  blue <- bands %>% filter(color=="blue") %>% select(min, max) %>% as.numeric()
  nir <- bands %>% filter(color=="nir") %>% select(min, max) %>% as.numeric()
  red <- bands %>% filter(color=="red") %>% select(min, max) %>% as.numeric()
  
  spectra_bands <- spectra %>% 
    mutate(color = ifelse(Wavelength >= blue[1] & Wavelength <= blue[2], "blue",
                          ifelse(Wavelength >= red[1] & Wavelength <= red[2], "red",
                                 ifelse(Wavelength >= nir[1] & Wavelength <= nir[2], "nir",
                                        "other")))) %>% 
    group_by(color) %>% 
    summarize(Reflectance = mean(Reflectance))
  
  index_data <- spectra_bands %>%
    spread(color, Reflectance) %>% 
    mutate(NDVI = (nir-red)/(nir+red),
           EVI = 2.5*((nir-red)/(nir+6*red-7.5*blue + 1)),
           EVI2 = 2.5*((nir-red)/(nir+2.4*red + 1))) %>% 
    select_at(indices) %>% 
    gather(Index, Value, everything())
  
  return(index_data) 
}

read_sc_spu_file <- function(fileName) {
  # prints .spu filelname to console 
  print(fileName)

  # get filenum
  path <- str_split(fileName, pattern = "/")[[1]]
  spu_filename <- last(path)
  file_info <- str_split(spu_filename, pattern = "\\.")[[1]]
  file_num <- file_info[1] %>% str_sub(start = 5L) %>% as.numeric()

  # # Read metadata from first 9 lines of .spu file
   text <- read_lines(fileName, n_max = 9)
  
  # Read spectral intensity data into dataframe
  data <- read.table(file = fileName, skip = 10, col.names = c("Wavelength", "Reflectance", "Reference"))  %>%  as_tibble() %>% 
    mutate(spu_filename = spu_filename, FileNum = file_num) %>% 
    nest(Spectra = c(Wavelength, Reflectance, Reference)) 
  
  return(data)
}



calculate_spectral_bands <- function(spectra, band_defns, instruments) {
  # Calculates spectral bands from dataframe including Wavelength & Reflectance
  ## inputs: spectra - Wavelength, Reflectance columns
  ##         band_defns : wavelengths definining colors 
  ##         instrument : e.g. MODIS, SKYE, ITEX
  ##         bands   : the spectral bands to return, e.g. red, blue, nir, etc. 
  ## output: spectra_bands = dataframe with Definition, Band, Averaged Reflectance
  
  bands <- band_defns %>% 
    filter(definition %in% instruments)
  
  # vector of wavelengths, one set per instrument
  wavelengths <- seq(300, 1500, by = 1)
  
  # dataframe of wavelengths labeled by instrument & color
  bands_df <- tibble(Wavelength = rep(wavelengths, times = length(instruments)), 
                     definition = rep(instruments, each = length(wavelengths))) %>% 
    full_join(bands) %>% 
    mutate(color_match = ifelse(Wavelength >= min & Wavelength <= max, color, NA)) %>% 
    select(Wavelength, definition, color_match) %>% 
    distinct()
  
  ## DATA: join to measured spectra 
  spectra_bands <- full_join(spectra, bands_df) %>% 
    group_by(definition, color_match) %>% 
    summarize(average_reflectance = mean(Reflectance)) %>% 
    filter(!is.na(color_match)) %>% 
    rename(band = color_match)
  
  return(spectra_bands) 
}
```


## Read-in SPU Files 
```{r}



# Set working directory
wdir <- "/home/ruby/Projects/toolik_phenology/unispec-sc/20220613/" #this is the path to the folder containing your (1) files and (2) field key
setwd(wdir)
# Create vector of ".spu" files 
spu_files <- list.files(path = wdir, pattern = ".spu$", full.names = T, recursive=T)
# Read-in files to a dataframe using "read_sc_spu_file" function from above 
spu_data <- map_dfr(spu_files, read_sc_spu_file) 
# Save spu data
# write_rds(spu_data, "spu_data.rds")
# spu_data <- read_rds("spu_data.rds")


## Read field key  LOCALLY
# field_key <- read_csv("unispec-sc_test_labels_2022-06-10.csv", skip_empty_rows = T) %>% 
#   filter(!is.na(spu_filename)) 

## Read field key from gsheets
file_link <- "https://docs.google.com/spreadsheets/d/13Y10L559_jJoyoxwkT_MjvfjYEPkFHwX0IUAH3Wsd9Y/edit#gid=0"

field_key <- read_sheet(file_link)

```

## Calculate NDVI
Take dafatframe of .spu data and calculate NDVI. 
```{r}
df_indices <- spu_data %>% mutate(Indices = map(Spectra, function(x) calculate_indices(x, band_defns = band_defns, instrument = "MODIS", indices = c("NDVI", "EVI", "EVI2"))))
df_spectra <- spu_data %>% mutate(Spectral_Bands = map(Spectra, function(x) calculate_spectral_bands(x, band_defns = band_defns, instrument = "MODIS")))
```


## Read-in Field Key
```{r}

## Unnest Spectra:
df_spectra <- spu_data %>% unnest(Spectra)

## Join with data
df <- left_join(field_key, df_spectra) %>% 
  mutate(Ratio = Reflectance/Reference)


## QUALITY CHECK: find null spectra
df %>%  filter(Spectra %>% map(is.null) %>% map_lgl(any)) 

### LOOK AT DATA SUMMARIES 
## Dataframe summary
df %>% group_by(Species) %>%
  summarize(Species = str_c(unique(Species), collapse = ", "), NumFiles = n())

```


## Plot any file
```{r}
# Expand Spectra information
# Plot faceting by block, instrument 
ggplot(df, aes(x=Wavelength, y = Ratio)) +
  geom_line(aes(color = factor(Color_Key_Value), group = FileNum)) + 
  facet_wrap(vars(Species))

# Subset 
df_subset <- spu_data %>% filter(!is.na(spu_filename))
fileName <- "unispec-sc_files/b3.cl1-1800001.spu"

```

